name: Update Sponsors
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨更新
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Update sponsors
        run: npx sponsorkit
        env:
          AFDIAN_USER_ID: ${{ secrets.AFDIAN_USER_ID }}
          AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sponsors.svg"
          file_pattern: "sponsors.*"